spring:
  application:
    name: Chronicles
  data:
    mongo:
#      host: localhost
#      port: 27017
    mongodb:
      uri: ${MONGODB_URI}
      database: my_journal_entries
      auto-index-creation: true
#      username: chronicles
#      password: 1234
  main:
    allow-circular-references: true



  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}           # feel free to add your email
    password:  ${MAIL_PASS}            # generate the 16 digit password form the Google app's settings "App passwords" and add it here. Its not the password of your account
    properties:
      mail:
        smtp:
          auth: true
          starttls:                   # start transport layer security
            enable: true              # encrypted text exchanges


server:
  port: 8080

weather:
  api:
    key: 999b35c4068fbeecd94830b6a758c7c3

#logging:
#  level:
#    com:
#      app:
#        Chronicles: DEBUG

#logging:
#  level:
#    root: ERROR # this will log only the error and its upper levels

#logging:
#  level:
#    com:
#      app:
#        Chronicles:
#          service:
#            UserService: OFF     # this will completely off the user service logging